url: https://wattlearn-www.github.io
#baseurl: /agency-jekyll-theme/

# Site settings
company: Watt-Learn
title: Homepage
email: info@wattlearn.com
description: "Watt-Learn | Intelligent Batteries for Reliable and Profitable Grid. Watt-Learn offers revolutionary cloud-based AI software for battery installations. Our AI platform maximizes ROI and life of battery projects at different scale."


# Team names, titles and social links
people:
- name: Matineh Eybpoosh, Ph.D.
  pic: 1
  position: CEO, Co-founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/matineh-eybpoosh-647b5134

- name: Puneeth Kalavase, Ph.D.
  pic: 2
  position: Lead Data Scientist
  social:
    - title: linkedin
      url: https://www.linkedin.com/puneeth-kalavase-0a378532

- name: Bo Olsen
  pic: 3
  position: Senior Software Engineer

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/company/watt-learn
  - title: stack-exchange
    url: https://math.stackexchange.com/questions/tagged/linear-programming
  - title: github
    url: http://github.com/watt-learn

# Postal address (add as many lines as necessary)
address:
  - line: 1 Superman street
  - line: Palo Alto, California 92037, USA

# Build settings
markdown: kramdown
permalink: pretty
